apiVersion: v1
kind: Service
metadata:
  name: {{ include "btn-rates-minikube.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "btn-rates-minikube.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "btn-rates-minikube.selectorLabels" . | nindent 4 }}